services:
  web:
    build: .
    ports:
      - "5110:5110"
    volumes:
      - ./uploads:/app/uploads
      - ./output:/app/output
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped